import { Link } from 'react-router-dom';
import { useShop } from '../context/ShopContext.tsx';
import FoodImage from './FoodImage';
import { money } from '../utils/money';
export default function OrderPanel() {
  const { source, sending, orderError, receipt, submitOrder, count, cart, items, subtotal, delivery, setDelivery, review, setReview, setCart, setNotice, change, customer, setCustomer } = useShop();
  return (        <aside id="pedido" className="order-panel">
          <div className="order-heading"><h2>Seu pedido <small>{count}</small></h2><button className="text-button" disabled={!count || sending} onClick={() => { setCart({}); setReview(false); setNotice('Pedido esvaziado.'); }}>Limpar</button></div>
          <div className="cart-items">{!count ? <div className="empty-cart"><h3>O que vai ser hoje?</h3><p>Seu pedido está vazio.<br />Adicione um lanche para começar.</p><Link to="/cardapio">Ver os lanches →</Link></div> : items.map(p => <div className="cart-item" key={p.id}><FoodImage src={p.imgUrl} name={p.nome}/><div className="cart-item-info"><h3>{p.nome}</h3><p>{money(p.preco * cart[p.id])}</p><div className="quantity"><button disabled={sending} aria-label={`Diminuir ${p.nome}`} onClick={() => change(p, -1)}>−</button><span>{cart[p.id]}</span><button disabled={sending} aria-label={`Aumentar ${p.nome}`} onClick={() => change(p, 1)}>+</button></div></div><button disabled={sending} className="remove" aria-label={`Remover ${p.nome}`} onClick={() => change(p, -cart[p.id])}>×</button></div>)}</div>
          <div className="order-summary"><div><span>Subtotal</span><span>{money(subtotal)}</span></div><div><span>{delivery ? 'Taxa de entrega' : 'Retirada no local'}</span><span>{delivery ? 'A confirmar' : 'Grátis'}</span></div><div className="total"><strong>Total dos produtos</strong><strong>{money(subtotal)}</strong></div></div>
          <form onSubmit={event => { event.preventDefault(); if (review) { void submitOrder(); } else { setReview(true); } }}>
            <fieldset disabled={sending} className="order-fields"><h3 className="form-heading">Entrega ou retirada?</h3><div className="delivery-toggle"><button type="button" className={delivery ? 'selected' : ''} onClick={() => { setDelivery(true); setReview(false); }}>Entrega</button><button type="button" className={!delivery ? 'selected' : ''} onClick={() => { setDelivery(false); setReview(false); }}>Retirar no local</button></div>
            <div className="customer-fields" onChange={() => setReview(false)}><label>Seu nome<input name="nome" value={customer.nome} onChange={event => setCustomer(current => ({ ...current, nome: event.target.value }))} placeholder="Como podemos te chamar?" autoComplete="name" required maxLength={80} pattern=".*\S.*"/></label><label>Telefone<input name="telefone" value={customer.telefone} onChange={event => setCustomer(current => ({ ...current, telefone: event.target.value }))} type="tel" placeholder="(00) 00000-0000" autoComplete="tel" required pattern={'[0-9\\s\\(\\)\\+\\.\\-]{10,20}'} title="Informe o telefone com DDD, usando entre 10 e 20 caracteres."/></label>{delivery && <><label>Endereço de entrega<input name="endereco" value={customer.endereco} onChange={event => setCustomer(current => ({ ...current, endereco: event.target.value }))} placeholder="Rua, número e bairro" autoComplete="street-address" required minLength={5} pattern=".*\S.*" maxLength={250}/></label><label>Complemento <span>(opcional)</span><input name="complemento" value={customer.complemento} onChange={event => setCustomer(current => ({ ...current, complemento: event.target.value }))} placeholder="Apartamento, bloco, referência…" maxLength={150}/></label></>}</div>
            <div className="payment-note"><div><strong>Pagamento na {delivery ? 'entrega' : 'retirada'}</strong><p>Combine a forma de pagamento com a loja.</p></div></div>
            <button className="primary checkout" disabled={!count || sending || source !== 'api'} type="submit">{sending ? 'Enviando…' : review ? 'Confirmar e enviar pedido' : 'Revisar pedido'} <span>→</span></button></fieldset>
            {review && <div className="review-message" role="status"><strong>Resumo: {count} {count === 1 ? 'item' : 'itens'} · {money(subtotal)}</strong><p>{delivery ? 'Entrega selecionada. Frete a confirmar.' : 'Retirada no local selecionada.'} Confira os dados acima e confirme para enviar à loja.</p></div>}
            {source === 'demo' && <p className="demo-note">O envio fica disponível quando o cardápio da loja estiver conectado.</p>}
            {orderError && <p className="review-message" role="alert">{orderError}</p>}
            {receipt && <div className="review-message" role="status"><strong>Pedido enviado!</strong><p><Link to={`/pedido/${receipt.id}`}>Acompanhar pedido →</Link></p><p>Número: {receipt.id}</p><p>Total dos produtos: {money(receipt.total)} · Status: {receipt.status}</p><p>Guarde este número para consultar com a loja.</p></div>}
          </form>
          <p className="order-footnote">Você pode conferir os itens antes de continuar.</p>
        </aside>
);
}
